require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'example.rb'
    - 'http-basic-example.rb'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.1

Naming/FileName:
  Exclude:
    - 'lib/jira-ruby.rb'

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'

# Temporarily Disable

Layout/LineLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

